### ISSUE TITLE
Failed to use .venv packages in python 3.12.1

### ISSUE THREAD

**Issue by Quanvm0501** [FujiwaraChoki/MoneyPrinter#146]
Bug:
I can't use virtualenv (a.k.a venv) to install the requirements because i want to get less memory to install

Desktop:
 - Windows
 - Firefox
 - Python 3.12.1

Output:
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [28 lines of output]
      Traceback (most recent call last):
        File "E:\Program Files\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "E:\Program Files\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "E:\Program Files\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Bilybo\AppData\Local\Temp\pip-build-env-rfj0i11h\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Bilybo\AppData\Local\Temp\pip-build-env-rfj0i11h\overlay\Lib\site-packages\setuptools\build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "C:\Users\Bilybo\AppData\Local\Temp\pip-build-env-rfj0i11h\overlay\Lib\site-packages\setuptools\build_meta.py", line 480, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "C:\Users\Bilybo\AppData\Local\Temp\pip-build-env-rfj0i11h\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 6, in <module>
        File "E:\Program Files\Python312\Lib\inspect.py", line 1282, in getsource
          lines, lnum = getsourcelines(object)
                        ^^^^^^^^^^^^^^^^^^^^^^
        File "E:\Program Files\Python312\Lib\inspect.py", line 1264, in getsourcelines
          lines, lnum = findsource(object)
                        ^^^^^^^^^^^^^^^^^^
        File "E:\Program Files\Python312\Lib\inspect.py", line 1093, in findsource
          raise OSError('could not get source code')
      OSError: could not get source code
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

Contact me at email: [qvu217720@gmail.com](mailto:qvu217720@gmail.com)

**Comment by vo1d-null** [comment]
pip install wheel
then try pip install -r requirements

**Comment by Quanvm0501** [comment]
@FujiwaraChoki , @vo1d-null 
It's same, I installed before and failed, tho.
I think it's the python 3.12.1 can't used.
I'll try in a python 3.11.6 later.
If I can't, I'll send to you, ok?

Screenshot:
![Screenshot 2024-02-10 220217](https://github.com/FujiwaraChoki/MoneyPrinter/assets/92785316/254b1a3e-9fd4-4090-93a8-cf1e0d7d68ed)

https://github.com/FujiwaraChoki/MoneyPrinter/assets/92785316/1ea247a5-6cd8-4485-939c-59911f346ba4

**Comment by FujiwaraChoki** [comment]
Venv not recommended
