### ISSUE TITLE
[BUG] pip install requirement ends with error

### ISSUE THREAD

**Issue by toutjavascript** [FujiwaraChoki/MoneyPrinter#162]
Hello

I am on Win 11, AMD ryzen CPU, RTX3070, 16GB

When I run  pip install -r requirements.txt, I got those errors: 

```

Collecting playsound==1.3.0 (from -r requirements.txt (line 9))
  Using cached playsound-1.3.0.tar.gz (7.7 kB)
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [28 lines of output]
      Traceback (most recent call last):
        File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2288.0_x64__qbz5n2kfra8p0\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2288.0_x64__qbz5n2kfra8p0\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2288.0_x64__qbz5n2kfra8p0\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\3950X\AppData\Local\Temp\pip-build-env-6siigbzw\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\3950X\AppData\Local\Temp\pip-build-env-6siigbzw\overlay\Lib\site-packages\setuptools\build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "C:\Users\3950X\AppData\Local\Temp\pip-build-env-6siigbzw\overlay\Lib\site-packages\setuptools\build_meta.py", line 480, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "C:\Users\3950X\AppData\Local\Temp\pip-build-env-6siigbzw\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 6, in <module>
        File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2288.0_x64__qbz5n2kfra8p0\Lib\inspect.py", line 1262, in getsource
          lines, lnum = getsourcelines(object)
                        ^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2288.0_x64__qbz5n2kfra8p0\Lib\inspect.py", line 1244, in getsourcelines
          lines, lnum = findsource(object)
                        ^^^^^^^^^^^^^^^^^^
        File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2288.0_x64__qbz5n2kfra8p0\Lib\inspect.py", line 1081, in findsource
          raise OSError('could not get source code')
      OSError: could not get source code
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

```

Could you help please ?

**Comment by pmavro** [comment]
tout take a look at this link ([link](https://github.com/termux/termux-app/discussions/3306#discussioncomment-6651045)) mentioned in #3, this helped fix this for me

**Comment by toutjavascript** [comment]
@pmavro thanks. It starts now

**Comment by pmavro** [comment]
happy to help!

**Comment by Shailendra1703** [comment]
@toutjavascript @petmav I tried both the commands mentioned in PR, but still the error persists. Here is the log I got
```
Collecting g4f (from -r requirements.txt (line 1))
  Using cached g4f-0.3.9.2-py3-none-any.whl.metadata (56 kB)
Requirement already satisfied: setuptools in c:\users\batman\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 2)) (75.6.0)
Requirement already satisfied: wheel in c:\users\batman\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 3)) (0.45.1)
Collecting requests==2.31.0 (from -r requirements.txt (line 4))
  Using cached requests-2.31.0-py3-none-any.whl.metadata (4.6 kB)
Collecting moviepy==1.0.3 (from -r requirements.txt (line 5))
  Using cached moviepy-1.0.3.tar.gz (388 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [56 lines of output]
      C:\Users\batman\AppData\Local\Temp\pip-install-y7vihu3o\moviepy_1976968ad9204357ba6b8df38cfccb82\setup.py:10: SetuptoolsDeprecationWarning: The test command is disabled and references to it are deprecated.
      !!

              ********************************************************************************
              Please remove any references to `setuptools.command.test` in all supported versions of the affected package.

              This deprecation is overdue, please update your project and remove deprecated
              calls to avoid build errors in the future.
              ********************************************************************************

      !!
        from setuptools.command.test import test as TestCommand
      C:\Users\batman\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\_distutils\dist.py:261: UserWarning: Unknown distribution option: 'tests_require'
        warnings.warn(msg)
      running egg_info
      creating C:\Users\batman\AppData\Local\Temp\pip-pip-egg-info-696svg7z\moviepy.egg-info
      writing C:\Users\batman\AppData\Local\Temp\pip-pip-egg-info-696svg7z\moviepy.egg-info\PKG-INFO
      writing dependency_links to C:\Users\batman\AppData\Local\Temp\pip-pip-egg-info-696svg7z\moviepy.egg-info\dependency_links.txt
      writing requirements to C:\Users\batman\AppData\Local\Temp\pip-pip-egg-info-696svg7z\moviepy.egg-info\requires.txt
      writing top-level names to C:\Users\batman\AppData\Local\Temp\pip-pip-egg-info-696svg7z\moviepy.egg-info\top_level.txt
      writing manifest file 'C:\Users\batman\AppData\Local\Temp\pip-pip-egg-info-696svg7z\moviepy.egg-info\SOURCES.txt'
      reading manifest file 'C:\Users\batman\AppData\Local\Temp\pip-pip-egg-info-696svg7z\moviepy.egg-info\SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      adding license file 'LICENCE.txt'
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\batman\AppData\Local\Temp\pip-install-y7vihu3o\moviepy_1976968ad9204357ba6b8df38cfccb82\setup.py", line 110, in <module>
          setup(
        File "C:\Users\batman\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\__init__.py", line 117, in setup
          return distutils.core.setup(**attrs)
        File "C:\Users\batman\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\_distutils\core.py", line 183, in setup
          return run_commands(dist)
        File "C:\Users\batman\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\_distutils\core.py", line 199, in run_commands
          dist.run_commands()
        File "C:\Users\batman\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\_distutils\dist.py", line 954, in run_commands
          self.run_command(cmd)
        File "C:\Users\batman\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\dist.py", line 995, in run_command
          super().run_command(command)
        File "C:\Users\batman\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\_distutils\dist.py", line 973, in run_command
          cmd_obj.run()
        File "C:\Users\batman\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\command\egg_info.py", line 313, in run
          self.find_sources()
        File "C:\Users\batman\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\command\egg_info.py", line 321, in find_sources
          mm.run()
        File "C:\Users\batman\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\command\egg_info.py", line 549, in run
          self.prune_file_list()
        File "C:\Users\batman\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\command\sdist.py", line 162, in prune_file_list
          super().prune_file_list()
        File "C:\Users\batman\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\_distutils\command\sdist.py", line 380, in prune_file_list
          base_dir = self.distribution.get_fullname()
        File "C:\Users\batman\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\_core_metadata.py", line 267, in get_fullname
          return _distribution_fullname(self.get_name(), self.get_version())
        File "C:\Users\batman\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\_core_metadata.py", line 285, in _distribution_fullname
          canonicalize_version(version, strip_trailing_zero=False),
      TypeError: canonicalize_version() got an unexpected keyword argument 'strip_trailing_zero'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```
