### ISSUE TITLE
[Help]how the setup the in unbutton??

### ISSUE THREAD

**Issue by justincnn** [FujiwaraChoki/MoneyPrinter#236]
I hv install the imagemagick by
~~~bash
apt install imagemagick
~~~

but how to set the below env:

~~~yaml
# ImageMagick Binary Path
# Download ImageMagick from https://imagemagick.org/script/download.php
IMAGEMAGICK_BINARY=""
~~~

**Comment by FujiwaraChoki** [comment]
`whereis convert`, copy the path to the env.

**Comment by justincnn** [comment]
> `whereis convert`, copy the path to the env.

sorry ,it does not work, pls help again ,tis

~~~
Traceback (most recent call last):
  File "/home/ubuntu/MoneyPrinter/Backend/main.py", line 12, in <module>
    from video import *
  File "/home/ubuntu/MoneyPrinter/Backend/video.py", line 9, in <module>
    from moviepy.editor import *
  File "/usr/local/lib/python3.10/dist-packages/moviepy/editor.py", line 36, in <module>
    from .video.io.VideoFileClip import VideoFileClip
  File "/usr/local/lib/python3.10/dist-packages/moviepy/video/io/VideoFileClip.py", line 3, in <module>
    from moviepy.audio.io.AudioFileClip import AudioFileClip
  File "/usr/local/lib/python3.10/dist-packages/moviepy/audio/io/AudioFileClip.py", line 3, in <module>
    from moviepy.audio.AudioClip import AudioClip
  File "/usr/local/lib/python3.10/dist-packages/moviepy/audio/AudioClip.py", line 7, in <module>
    from moviepy.audio.io.ffmpeg_audiowriter import ffmpeg_audiowrite
  File "/usr/local/lib/python3.10/dist-packages/moviepy/audio/io/ffmpeg_audiowriter.py", line 7, in <module>
    from moviepy.config import get_setting
  File "/usr/local/lib/python3.10/dist-packages/moviepy/config.py", line 82, in <module>
    raise IOError("%s - The path specified for the ImageMagick binary might "
OSError: [Errno 13] Permission denied: '/usr/share/man/man1/convert.1.gz' - The path specified for the ImageMagick binary might be wrong: /usr/share/man/man1/convert.1.gz
~~~
