### ISSUE TITLE
This error is prompted when running python3 main.py

### ISSUE THREAD

**Issue by 125540947** [FujiwaraChoki/MoneyPrinter#244]
![Uploading 微信图片_202403180
![微信图片_20240318004620](https://github.com/FujiwaraChoki/MoneyPrinter/assets/38803156/a26531bc-3032-4dba-ad82-3ee653f3f477)
04620.png…](

Traceback (most recent call last):
  File "main.py", line 11, in <module>
    from gpt import *
  File "/root/MoneyPrinter/Backend/gpt.py", line 9, in <module>
    import google.generativeai as genai
  File "/usr/local/lib/python3.8/dist-packages/google/generativeai/__init__.py", line 55, in <module>
    from google.generativeai import types
  File "/usr/local/lib/python3.8/dist-packages/google/generativeai/types/__init__.py", line 17, in <module>
    from google.generativeai.types.discuss_types import *
  File "/usr/local/lib/python3.8/dist-packages/google/generativeai/types/discuss_types.py", line 21, in <module>
    import google.ai.generativelanguage as glm
  File "/usr/local/lib/python3.8/dist-packages/google/ai/generativelanguage/__init__.py", line 21, in <module>
    from google.ai.generativelanguage_v1beta2.services.discuss_service.async_client import (
  File "/usr/local/lib/python3.8/dist-packages/google/ai/generativelanguage_v1beta2/__init__.py", line 21, in <module>
    from .services.discuss_service import DiscussServiceAsyncClient, DiscussServiceClient
  File "/usr/local/lib/python3.8/dist-packages/google/ai/generativelanguage_v1beta2/services/discuss_service/__init__.py", line 16, in <module>
    from .async_client import DiscussServiceAsyncClient
  File "/usr/local/lib/python3.8/dist-packages/google/ai/generativelanguage_v1beta2/services/discuss_service/async_client.py", line 32, in <module>
    from google.api_core import gapic_v1
  File "/usr/local/lib/python3.8/dist-packages/google/api_core/gapic_v1/__init__.py", line 16, in <module>
    from google.api_core.gapic_v1 import config
  File "/usr/local/lib/python3.8/dist-packages/google/api_core/gapic_v1/config.py", line 23, in <module>
    import grpc
ModuleNotFoundError: No module named 'grpc'

**Comment by FujiwaraChoki** [comment]
pip install grpc
