### ISSUE TITLE
[BUG] pip install requirements fail at playsound

### ISSUE THREAD

**Issue by vishnuvardhan2005** [FujiwaraChoki/MoneyPrinter#246]
**Describe the bug**
pip install fail at playsound

**To Reproduce**
1. Clone the repo
2. Run pip install -r requirements

**Expected behavior**
Error:
Collecting playsound (from -r .\requirements.txt (line 9))
  Using cached playsound-1.3.0.tar.gz (7.7 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [28 lines of output]
      Traceback (most recent call last):
        File "C:\code\Python\MoneyPrinter\venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\code\Python\MoneyPrinter\venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\code\Python\MoneyPrinter\venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\vishn\AppData\Local\Temp\pip-build-env-5f5xa_qd\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\vishn\AppData\Local\Temp\pip-build-env-5f5xa_qd\overlay\Lib\site-packages\setuptools\build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "C:\Users\vishn\AppData\Local\Temp\pip-build-env-5f5xa_qd\overlay\Lib\site-packages\setuptools\build_meta.py", line 487, in run_setup
          super().run_setup(setup_script=setup_script)
        File "C:\Users\vishn\AppData\Local\Temp\pip-build-env-5f5xa_qd\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 6, in <module>
        File "C:\Users\vishn\AppData\Local\Programs\Python\Python312\Lib\inspect.py", line 1282, in getsource
          lines, lnum = getsourcelines(object)
                        ^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\vishn\AppData\Local\Programs\Python\Python312\Lib\inspect.py", line 1264, in getsourcelines
          lines, lnum = findsource(object)
                        ^^^^^^^^^^^^^^^^^^
        File "C:\Users\vishn\AppData\Local\Programs\Python\Python312\Lib\inspect.py", line 1093, in findsource
          raise OSError('could not get source code')
      OSError: could not get source code
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.

**Screenshots**
NA

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Python Version [3.12.2]

**Comment by FujiwaraChoki** [comment]
FAQ section

**Comment by vishnuvardhan2005** [comment]
ah ok. Thank you.
