### ISSUE TITLE
error: subprocess-exited-with-error when running pip install command

### ISSUE THREAD

**Issue by DevShaded** [FujiwaraChoki/MoneyPrinter#3]
When I run `pip install -r requirements.txt` on my Windows 11 Pro machine I get an error back like this

Python version: `Python 3.12.1`
Pip version: `pip 23.3.2`

```bash
>pip install -r requirements.txt
Collecting g4f (from -r requirements.txt (line 1))
  Using cached g4f-0.2.0.9-py3-none-any.whl.metadata (43 kB)
Requirement already satisfied: wheel in c:\python312\lib\site-packages (from -r requirements.txt (line 2)) (0.42.0)
Collecting requests (from -r requirements.txt (line 3))
  Using cached requests-2.31.0-py3-none-any.whl.metadata (4.6 kB)
Collecting moviepy (from -r requirements.txt (line 4))
  Using cached moviepy-1.0.3.tar.gz (388 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting termcolor (from -r requirements.txt (line 5))
  Using cached termcolor-2.4.0-py3-none-any.whl.metadata (6.1 kB)
Collecting flask (from -r requirements.txt (line 6))
  Using cached flask-3.0.1-py3-none-any.whl.metadata (3.6 kB)
Collecting flask-cors (from -r requirements.txt (line 7))
  Using cached Flask_Cors-4.0.0-py2.py3-none-any.whl.metadata (5.4 kB)
Collecting playsound (from -r requirements.txt (line 8))
  Using cached playsound-1.3.0.tar.gz (7.7 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [28 lines of output]
      Traceback (most recent call last):
        File "C:\Users\fredr.DESKTOP-DTV2HJ8\AppData\Roaming\Python\Python312\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\fredr.DESKTOP-DTV2HJ8\AppData\Roaming\Python\Python312\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\fredr.DESKTOP-DTV2HJ8\AppData\Roaming\Python\Python312\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\fredr.DESKTOP-DTV2HJ8\AppData\Local\Temp\pip-build-env-_k5xxtt6\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\fredr.DESKTOP-DTV2HJ8\AppData\Local\Temp\pip-build-env-_k5xxtt6\overlay\Lib\site-packages\setuptools\build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "C:\Users\fredr.DESKTOP-DTV2HJ8\AppData\Local\Temp\pip-build-env-_k5xxtt6\overlay\Lib\site-packages\setuptools\build_meta.py", line 480, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "C:\Users\fredr.DESKTOP-DTV2HJ8\AppData\Local\Temp\pip-build-env-_k5xxtt6\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 6, in <module>
        File "C:\Python312\Lib\inspect.py", line 1282, in getsource
          lines, lnum = getsourcelines(object)
                        ^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Python312\Lib\inspect.py", line 1264, in getsourcelines
          lines, lnum = findsource(object)
                        ^^^^^^^^^^^^^^^^^^
        File "C:\Python312\Lib\inspect.py", line 1093, in findsource
          raise OSError('could not get source code')
      OSError: could not get source code
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by DevShaded** [comment]
Those didn't help me, but I found this discussion thread and it worked! https://github.com/termux/termux-app/discussions/3306#discussioncomment-6651045

**Comment by FujiwaraChoki** [comment]
> Those didn't help me, but I found this discussion thread and it worked! [termux/termux-app#3306 (reply in thread)](https://github.com/termux/termux-app/discussions/3306#discussioncomment-6651045)

Nice, although it's pretty weird, as the second requirement is `wheel`. I'll make sure to add `setuptools` as well. Thank you!
