### ISSUE TITLE
AttributeError: module 'attr' has no attribute 's'[BUG]

### ISSUE THREAD

**Issue by effnorwood** [FujiwaraChoki/MoneyPrinter#67]
I'm running this on Ubuntu Linux server LTS, python 3. First issue - that works yes or does it need Windows instead?

Issue:
/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (2.2.0) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
Traceback (most recent call last):
  File "main.py", line 3, in <module>
    from gpt import *
  File "/home/eff/MoneyPrinter/Backend/gpt.py", line 3, in <module>
    import g4f
  File "/home/eff/.local/lib/python3.8/site-packages/g4f/__init__.py", line 6, in <module>
    from .models   import Model, ModelUtils
  File "/home/eff/.local/lib/python3.8/site-packages/g4f/models.py", line 3, in <module>
    from .Provider   import RetryProvider, ProviderType
  File "/home/eff/.local/lib/python3.8/site-packages/g4f/Provider/__init__.py", line 5, in <module>
    from .base_provider   import AsyncProvider, AsyncGeneratorProvider
  File "/home/eff/.local/lib/python3.8/site-packages/g4f/Provider/base_provider.py", line 9, in <module>
    from .helper import get_cookies, format_prompt
  File "/home/eff/.local/lib/python3.8/site-packages/g4f/Provider/helper.py", line 7, in <module>
    from aiohttp import BaseConnector
  File "/home/eff/.local/lib/python3.8/site-packages/aiohttp/__init__.py", line 6, in <module>
    from .client import (
  File "/home/eff/.local/lib/python3.8/site-packages/aiohttp/client.py", line 38, in <module>
    from . import hdrs, http, payload
  File "/home/eff/.local/lib/python3.8/site-packages/aiohttp/http.py", line 7, in <module>
    from .http_parser import (
  File "/home/eff/.local/lib/python3.8/site-packages/aiohttp/http_parser.py", line 30, in <module>
    from .helpers import (
  File "/home/eff/.local/lib/python3.8/site-packages/aiohttp/helpers.py", line 229, in <module>
    @attr.s(auto_attribs=True, frozen=True, slots=True)

Thanks

**Comment by FujiwaraChoki** [comment]
Not an issue with MoneyPrinter.
