### ISSUE TITLE
help with issue not finding ImageMagick

### ISSUE THREAD

**Issue by gulkily** [FujiwaraChoki/MoneyPrinter#84]
**Describe the bug**
Installing on Ubuntu WSL, Backend/main.py fails because it's not able to find ImageMagick binary. However, it is already installed on the system, and `which convert` returns /usr/bin/convert

**To Reproduce**
1. Do a fresh install using instructions in the readme
2. Get to the part where I `cd Backend` and `python3 main.py`
3. Run `python3 main.py`
4. See error:

(venv) wsl@Lenovo:~/MoneyPrinter/Backend$ python3 main.py
WARNING:playsound:playsound is relying on another python subprocess. Please use `pip install pygobject` if you want playsound to run more efficiently.
 * Serving Flask app 'main'
 * Debug mode: on
INFO:werkzeug:WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://172.29.47.13:8080
INFO:werkzeug:Press CTRL+C to quit
INFO:werkzeug: * Restarting with stat
Traceback (most recent call last):
  File "/home/wsl/MoneyPrinter/Backend/main.py", line 4, in <module>
    from video import *
  File "/home/wsl/MoneyPrinter/Backend/video.py", line 9, in <module>
    from moviepy.editor import *
  File "/home/wsl/MoneyPrinter/venv/lib/python3.10/site-packages/moviepy/editor.py", line 36, in <module>
    from .video.io.VideoFileClip import VideoFileClip
  File "/home/wsl/MoneyPrinter/venv/lib/python3.10/site-packages/moviepy/video/io/VideoFileClip.py", line 3, in <module>
    from moviepy.audio.io.AudioFileClip import AudioFileClip
  File "/home/wsl/MoneyPrinter/venv/lib/python3.10/site-packages/moviepy/audio/io/AudioFileClip.py", line 3, in <module>
    from moviepy.audio.AudioClip import AudioClip
  File "/home/wsl/MoneyPrinter/venv/lib/python3.10/site-packages/moviepy/audio/AudioClip.py", line 7, in <module>
    from moviepy.audio.io.ffmpeg_audiowriter import ffmpeg_audiowrite
  File "/home/wsl/MoneyPrinter/venv/lib/python3.10/site-packages/moviepy/audio/io/ffmpeg_audiowriter.py", line 7, in <module>
    from moviepy.config import get_setting
  File "/home/wsl/MoneyPrinter/venv/lib/python3.10/site-packages/moviepy/config.py", line 67, in <module>
    raise IOError(
OSError: ImageMagick binary cannot be found at

**Expected behavior**
Expected the backend to begin running

**Screenshots**
![image](https://github.com/FujiwaraChoki/MoneyPrinter/assets/1530699/81303c54-716b-4de6-b538-bb5da490f666)

**Desktop (please complete the following information):**
 - OS: Windows + Ubuntu WSL
 - Browser N/A
 - Python Version 3.10.12

**Additional context**
N/A

**Comment by gulkily** [comment]
Solved with:

export IMAGEMAGICK_BINARY=/usr/bin/convert
